language: ruby
rvm:
  - 2.1.0
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: ruby run-poll.rb
env:
  - R=1
  - R=2
  - R=3
  - R=4
  - R=5
  - R=6
  - R=7
  - R=8
  - R=9
  - R=10
  - R=11
  - R=12
  - R=13
  - R=14
  - R=15
  - R=16
  - R=17
  - R=18
  - R=19
  - R=20
  - R=21
  - R=22
  - R=23
  - R=24
  - R=25
  - R=26
  - R=27
  - R=28
  - R=29
  - R=30
  - R=31
  - R=32
  - R=33
  - R=34
  - R=35
  - R=36
  - R=37
  - R=38
  - R=39
  - R=40
  - R=41
  - R=42
  - R=43
  - R=44
  - R=45
  - R=46
  - R=47
  - R=48
  - R=49
  - R=50
  - R=51
  - R=52
  - R=53
  - R=54
  - R=55
  - R=56
  - R=57
  - R=58
  - R=59
  - R=60
  - R=61
  - R=62
  - R=63
  - R=64
  - R=65
  - R=66
  - R=67
  - R=68
  - R=69
  - R=70
  - R=71
  - R=72
  - R=73
  - R=74
  - R=75
  - R=76
  - R=77
  - R=78
  - R=79
  - R=80
  - R=81
  - R=82
  - R=83
  - R=84
  - R=85
  - R=86
  - R=87
  - R=88
  - R=89
  - R=90
  - R=91
  - R=92
  - R=93
  - R=94
  - R=95
  - R=96
  - R=97
  - R=98
  - R=99
  - R=100
